### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#1]
Develop contribution guide to mention steps which developers can follow and develop features effectively.

Reference Link: https://www.loom.com/share/bf121a44a5af46ccbb9315328f97bf75?sid=86a6734e-f529-4c25-871b-eb52e9dba485

**Comment by musangamfure** [comment]
Let me do this too

**Comment by rt4914** [comment]
Closing this for now as it is getting covered in #2
