### ISSUE TITLE
[Feature Request]: Add money-rails gem with oxr configuration

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#20]
### Is your feature request related to a problem? Please describe.

We want to manage currency for various services by doctor. For this we need money-rails and oxr gems

### Describe the solution you'd like

Reference: https://youtu.be/X1dvnG_Jux4
https://youtu.be/FzUZRdn7Qi4

**Comment by vanamraghu** [comment]
I will work on this issue
