### ISSUE TITLE
Codeowner template

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#3]
Add Codeowner template
Mention @rt4914 as codeowner for now.

References:
https://github.com/forem/forem/blob/main/.github/CODEOWNERS
https://github.com/oppia/oppia-android/blob/develop/.github/CODEOWNERS

**Comment by rt4914** [comment]
@KvngJamesNG I have assigned you this issue to work on.

**Comment by KvngJamesNG** [comment]
@rt4914 I have created the pull request and made changes as instructed.
many thanks

**Comment by rt4914** [comment]
@KvngJamesNG I missed on thing in this PR review. Your named the file `add-CODEOWNERS-template)` which is incorrect.
It should be `CODEOWNERS`named in `.github` folder. Similar to the links I shared above.

**Comment by KvngJamesNG** [comment]
@rt4914 file has been moved into .github folder..
Thank you for the observation
