### ISSUE TITLE
[Feature Request]: Add jwt token based authentication for signup and login

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#31]
### Is your feature request related to a problem? Please describe.

Our apis needs to be authenticated so for that we will use jwt-tokens

### Describe the solution you'd like

Reference: https://www.youtube.com/watch?v=Wq9i77BUBlQ
Reference: https://youtu.be/OmT_uNtT7vY

Implement jwt token based authentication

https://dakotaleemartinez.com/tutorials/devise-jwt-api-only-mode-for-authentication/

**Comment by vanamraghu** [comment]
I will work on this
