### ISSUE TITLE
[Feature Request]: Add MoneyRails gem

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#48]
### Is your feature request related to a problem? Please describe.

Add MoneyRails gem

### Describe the solution you'd like

Add MoneyRails gem https://www.rubydoc.info/gems/money-rails/1.7.0

**Comment by rray524** [comment]
@KvngJamesNG can I work on this as this feature is pre-dependent of my assigned feature: #49 ?

**Comment by KvngJamesNG** [comment]
@rray524 I appreciate you reaching out about this.... 
Also sincere apologies for the delay I thought it has been unassigned before now.

but thanks for reaching out and yes you can work on this issue.

regards
