### ISSUE TITLE
Environment Requirements 

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#6]
Mention things which are required to run the project locally like rails version, ruby version, etc.

**Comment by KvngJamesNG** [comment]
I think I should battle this one

**Comment by KvngJamesNG** [comment]
I think I can battle this one

**Comment by rt4914** [comment]
@KvngJamesNG I am assigning you a different issue as this one is not required. It is getting covered in contribution Guide.
