### ISSUE TITLE
[Feature Request]: Review model should contain rating and comment

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#65]
### Is your feature request related to a problem? Please describe.

Review model should contain rating and comment

### Describe the solution you'd like

Review model should contain rating and comment

Rating can be 1,2,3,4,5 values
and comment can be of maximum 500 characters.

Comment is optional
Rating is mandatory.

Along with this in seeds.rb file add fake data too for reviews (there is already commented code, uncomment and edit it.)

**Comment by KvngJamesNG** [comment]
@rray524 working on it but youre the boss, you can have it. 👍🏾

**Comment by rray524** [comment]
thanks buddy, if you already started working on it plz continue by pushing your code.

**Comment by KvngJamesNG** [comment]
i ran into a bit of issue with the review rating seed code not allowing null value

i will try fix it today but still if you have the solution at your end fully working you can always push... 

i will be glad to learn one or two things from your code

**Comment by rray524** [comment]
@KvngJamesNG i have pushed the code, let me know if you need any help plz. thanks buddy!!
