### ISSUE TITLE
Add Database Design

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#7]
Mention the basic database design structure and add it to wiki.

**Comment by vanamraghu** [comment]
DB Design is added under wiki (Created new page DB Design)

**Comment by rt4914** [comment]
@rray524 Removed you from the issue as it was already assigned to me. Please make sure that you assign yourself to a non-assigned issue only.

**Comment by rt4914** [comment]
https://github.com/rt4914/KlinicCon-Backend/wiki/DB-Design
