### ISSUE TITLE
Add Devise Gem with configurable

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Backend#8]
Add Devise Gem with configurable. Making sure that it is api's only. You can test the APIs using Postman.

You should pick this task only if you know Postman and know how to create APIs in rails. If you don't know that please watch below videos before assigning yourself.

Reference: https://www.youtube.com/watch?v=Wq9i77BUBlQ
Reference: https://youtu.be/OmT_uNtT7vY

**Comment by vanamraghu** [comment]
I will work on this issue

**Comment by rt4914** [comment]
@vanamraghu Thanks. Try to prioritise this issue as it will be a blocker for many other issues. If it takes time do let me know and i will collaborate with you on the PR you create.
